/*
 * Copyright 2011-2025 JetBrains s.r.o. Use of this source code is governed by the Apache 2.0 license that can be found in the LICENSE file.
 */

package org.intellij.grammar.actions;

import java.io.File;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.io.FileOutputStream;
import java.nio.charset.StandardCharsets;

/**
 * A stand-in for a user's generator script, spawned by {@code GrammarKitCliRunnerRunPlatformTest}.
 *
 * <p>Deliberately plain Java with no dependencies at all: the test runs it in a bare JVM whose
 * classpath is only the directory this class was loaded from, so anything else — the Kotlin
 * standard library included — would not be there.
 *
 * <p>Writes a file per {@code --out} argument and reports it the way the contract asks. Every
 * other argument is ignored, which is what lets the runner append the grammar paths as usual.
 *
 * <pre>EchoGeneratedMain [--exit &lt;code&gt;] [--out &lt;file&gt;]... [ignored]...</pre>
 */
public final class EchoGeneratedMain {

  public static void main(String[] args) throws IOException {
    int exitCode = 0;
    for (int i = 0; i < args.length; i++) {
      if ("--exit".equals(args[i]) && i + 1 < args.length) {
        exitCode = Integer.parseInt(args[++i]);
      }
      else if ("--out".equals(args[i]) && i + 1 < args.length) {
        write(new File(args[++i]));
      }
    }
    System.out.flush();
    System.exit(exitCode);
  }

  private static void write(File file) throws IOException {
    File parent = file.getParentFile();
    if (parent != null) {
      //noinspection ResultOfMethodCallIgnored
      parent.mkdirs();
    }
    try (Writer writer = new OutputStreamWriter(new FileOutputStream(file), StandardCharsets.UTF_8)) {
      writer.write("generated by " + EchoGeneratedMain.class.getName() + "\n");
    }
    System.out.println(GrammarKitCliRunner.GENERATED_MARKER + " " + file.getAbsolutePath());
  }
}
