/*
 * Copyright 2011-2025 JetBrains s.r.o. Use of this source code is governed by the Apache 2.0 license that can be found in the LICENSE file.
 */

package org.intellij.grammar.generator;

import org.intellij.grammar.psi.BnfRule;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * This interface provides methods for generating identifiers for
 * various components in the parsers generated by the plugin.
 * It was created as a means of specifying the format of identifiers
 * for different programming languages (in our case, Java and Kotlin).
 */
public interface Renderer {

  /**
   * Given the function name returned previously from the {@link Renderer#getFuncName}
   * method and the index number, returns a new name constructed from the two values.
   */
  @NotNull String getNextName(@NotNull String funcName, int i);

  /**
   * Given a bnf rule, returns the name of the method used in the generated
   * parser to implement handling this rule. This method takes into account
   * the rules regarding identifier tokens in the target language.
   */
  @NotNull String getFuncName(@NotNull BnfRule rule);

  /**
   * Given a nested method name (typically produced by {@link Renderer#getNextName}),
   * returns the name of the wrapper meta-method that holds a {@code Parser}
   * instance for it. Meta-methods take other {@code Parser} instances as
   * parameters and return a {@code Parser} instance themselves; they are
   * used to lift inline expressions and meta-rule bodies into reusable parsers.
   */
  @NotNull String getWrapperParserMetaMethodName(@NotNull String nextName);

  /**
   * Returns a human-readable display name for the given rule, used as the
   * frame name in generated parser code (and in error messages produced
   * from it), or {@code null} when no display name is available.
   * <p>
   * The name is taken from the rule's {@link org.intellij.grammar.KnownAttribute#NAME}
   * attribute when set. Otherwise, when {@code force} is {@code true}, a name
   * is derived from the rule's function name; when {@code force} is
   * {@code false}, {@code null} is returned in that case.
   */
  @Nullable String getRuleDisplayName(@NotNull BnfRule rule, boolean force);
}
