/*
 * Copyright 2011-2025 JetBrains s.r.o. Use of this source code is governed by the Apache 2.0 license that can be found in the LICENSE file.
 */

package org.intellij.grammar.generator;

import org.intellij.grammar.psi.BnfRule;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * This interface provides methods for generating identifiers for
 * various components in the parsers generated by the plugin.
 * It was created as a means of specifying the format of identifiers
 * for different programming languages (in our case, Java and Kotlin).
 */
public interface Renderer {

  /**
   * Given the function name returned previously from the {@link Renderer#getFuncName}
   * method and the index number, returns a new name constructed from the two values.
   */
  @NotNull String getNextName(@NotNull String funcName, int i);

  /**
   * Given a bnf rule, returns the name of the method used in the generated
   * parser to implement handling this rule. This method takes into account
   * the rules regarding identifier tokens in the target language.
   */
  @NotNull String getFuncName(@NotNull BnfRule rule);

  @NotNull String getWrapperParserMetaMethodName(@NotNull String nextName);

  @Nullable String getRuleDisplayName(@NotNull BnfRule rule, boolean force);
}
